# Generated by Django 2.2.4 on 2019-11-21 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('module_name', models.CharField(max_length=200, null=True, verbose_name='模块名')),
                ('moule_detail', models.CharField(max_length=200, null=True, verbose_name='模块信息')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=200, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='密码')),
                ('pet_name', models.CharField(max_length=200, null=True, verbose_name='昵称')),
            ],
        ),
        migrations.CreateModel(
            name='WechatType',
            fields=[
                ('wechat_type_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('wechat_title', models.CharField(max_length=200, null=True, verbose_name='微信号标题')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.Module', verbose_name='模块')),
            ],
        ),
        migrations.CreateModel(
            name='WechatDetail',
            fields=[
                ('wechat_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('publish_time', models.DateField(null=True, verbose_name='发布时间')),
                ('area', models.CharField(max_length=200, null=True, verbose_name='地区')),
                ('attention', models.IntegerField(null=True, verbose_name='关注度')),
                ('assess', models.IntegerField(null=True, verbose_name='评价度')),
                ('detail', models.CharField(max_length=1000, null=True, verbose_name='详情介绍')),
                ('head_img', models.CharField(max_length=1000, null=True, verbose_name='头像（路径）')),
                ('ocr_img', models.CharField(max_length=1000, null=True, verbose_name='二维码（路径）')),
                ('is_pay', models.CharField(max_length=200, null=True, verbose_name='是否缴费(1,0)')),
                ('pay_level', models.CharField(max_length=200, null=True, verbose_name='缴费级别')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.WechatType', verbose_name='类别')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('tip_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('tip_name', models.CharField(max_length=200, null=True, verbose_name='标签名')),
                ('wechat', models.ManyToManyField(to='wechat.WechatDetail')),
            ],
        ),
    ]
