# Generated by Django 2.2.4 on 2019-12-30 13:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=200, null=True, verbose_name='昵称')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='邮箱')),
                ('avatar', models.FileField(default='avatars/default.png', upload_to='avatars/')),
                ('brithday', models.DateField(null=True, verbose_name='生日')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('experience', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=20)),
                ('area', models.CharField(max_length=200, null=True, verbose_name='地区')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('abstract', models.CharField(max_length=200, verbose_name='文章摘要')),
                ('desc', models.CharField(max_length=10000, verbose_name='文章描述')),
                ('group_cover', models.CharField(max_length=200, null=True, verbose_name='封面图')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField()),
                ('comment_count', models.IntegerField(default=0)),
                ('up_count', models.IntegerField(default=0)),
                ('down_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='分类标题')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=32, verbose_name='行业')),
            ],
            options={
                'db_table': 'wechat_wechat_profession',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='标签名称')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=32, verbose_name='标题')),
            ],
            options={
                'db_table': 'wechat_wechat_topic',
            },
        ),
        migrations.CreateModel(
            name='WechatGroup',
            fields=[
                ('profession', models.CharField(max_length=200, null=True, verbose_name='行业')),
                ('area', models.CharField(max_length=200, null=True, verbose_name='地区')),
                ('nik_name', models.CharField(max_length=200, null=True, verbose_name='名称')),
                ('tag', models.CharField(max_length=200, null=True, verbose_name='标签')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='联系人电话')),
                ('qq', models.CharField(max_length=200, null=True, verbose_name='联系人qq号')),
                ('avatars', models.CharField(max_length=200, null=True, verbose_name='头像')),
                ('qrc', models.CharField(max_length=200, null=True, verbose_name='群二维码')),
                ('introduce', models.CharField(max_length=10000, null=True, verbose_name='介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200, null=True, verbose_name='类别（微信红包，普通）')),
                ('master_wechat_account', models.CharField(max_length=200, null=True, verbose_name='群主微信号')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='联系人')),
                ('stataus', models.CharField(max_length=200, null=True, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'wechat_wechatgroup',
            },
        ),
        migrations.CreateModel(
            name='Stroy',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('desc', models.CharField(max_length=1000, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'wechat_story',
            },
        ),
        migrations.CreateModel(
            name='SellWechatGroup',
            fields=[
                ('profession', models.CharField(max_length=200, null=True, verbose_name='行业')),
                ('area', models.CharField(max_length=200, null=True, verbose_name='地区')),
                ('nik_name', models.CharField(max_length=200, null=True, verbose_name='名称')),
                ('tag', models.CharField(max_length=200, null=True, verbose_name='标签')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='联系人电话')),
                ('qq', models.CharField(max_length=200, null=True, verbose_name='联系人qq号')),
                ('avatars', models.CharField(max_length=200, null=True, verbose_name='头像')),
                ('qrc', models.CharField(max_length=200, null=True, verbose_name='群二维码')),
                ('introduce', models.CharField(max_length=10000, null=True, verbose_name='介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('p_count', models.CharField(max_length=200, null=True, verbose_name='人数')),
                ('price', models.CharField(max_length=200, null=True, verbose_name='价格')),
                ('master_wechat_account', models.CharField(max_length=200, null=True, verbose_name='群主微信号')),
                ('group_cover', models.CharField(max_length=200, null=True, verbose_name='群封面')),
                ('master_wechat_qrc', models.CharField(max_length=200, null=True, verbose_name='群主微信二维码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'wechat_sellwechatgroup',
            },
        ),
        migrations.CreateModel(
            name='SelfWechat',
            fields=[
                ('profession', models.CharField(max_length=200, null=True, verbose_name='行业')),
                ('area', models.CharField(max_length=200, null=True, verbose_name='地区')),
                ('nik_name', models.CharField(max_length=200, null=True, verbose_name='名称')),
                ('tag', models.CharField(max_length=200, null=True, verbose_name='标签')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='联系人电话')),
                ('qq', models.CharField(max_length=200, null=True, verbose_name='联系人qq号')),
                ('avatars', models.CharField(max_length=200, null=True, verbose_name='头像')),
                ('qrc', models.CharField(max_length=200, null=True, verbose_name='群二维码')),
                ('introduce', models.CharField(max_length=10000, null=True, verbose_name='介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('brithday', models.DateField(auto_now_add=True, verbose_name='生日')),
                ('wechat', models.CharField(max_length=200, null=True, verbose_name='卖点介绍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'wechat_selfwechat',
            },
        ),
        migrations.CreateModel(
            name='PublicWechat',
            fields=[
                ('profession', models.CharField(max_length=200, null=True, verbose_name='行业')),
                ('area', models.CharField(max_length=200, null=True, verbose_name='地区')),
                ('nik_name', models.CharField(max_length=200, null=True, verbose_name='名称')),
                ('tag', models.CharField(max_length=200, null=True, verbose_name='标签')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='联系人电话')),
                ('qq', models.CharField(max_length=200, null=True, verbose_name='联系人qq号')),
                ('avatars', models.CharField(max_length=200, null=True, verbose_name='头像')),
                ('qrc', models.CharField(max_length=200, null=True, verbose_name='群二维码')),
                ('introduce', models.CharField(max_length=10000, null=True, verbose_name='介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('wehcat_id', models.CharField(max_length=200, null=True, verbose_name='公众号id')),
                ('group_cover', models.CharField(max_length=200, null=True, verbose_name='群封面')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'wechat_publicwechat',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='图片名')),
                ('desc', models.CharField(max_length=255, verbose_name='图片描述')),
                ('type', models.CharField(max_length=50, verbose_name='分类')),
                ('src', models.CharField(max_length=50, verbose_name='路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'wechat_image',
            },
        ),
        migrations.CreateModel(
            name='Article2Tag',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Article', verbose_name='文章')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Tag', verbose_name='标签')),
            ],
            options={
                'unique_together': {('article', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='wechat.Article2Tag', to='wechat.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='品牌标题')),
                ('goodness', models.CharField(max_length=500, verbose_name='品牌优势')),
                ('desc', models.CharField(max_length=500, verbose_name='品牌描述')),
                ('qrc', models.CharField(max_length=500, verbose_name='微信号二维码')),
                ('wechat', models.CharField(max_length=500, verbose_name='微信号')),
                ('link', models.CharField(max_length=500, verbose_name='联系人')),
                ('phone', models.CharField(max_length=500, verbose_name='电话')),
                ('qq', models.CharField(max_length=500, verbose_name='qq')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'wechat_advert',
            },
        ),
    ]
